name: Build & Deploy Landscape

on:
  push:
    branches: [ main ]      # startet den Build bei jedem Commit auf main
  workflow_dispatch:         # erlaubt manuelles Starten

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Repository-Inhalt holen
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Neueste landscape2-Version installieren (automatisch via GitHub API)
      - name: Install landscape2 (latest linux amd64)
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p "$HOME/bin"

          # Neueste Release ermitteln und passende Binary-URL holen
          API_URL="https://api.github.com/repos/cncf/landscape2/releases/latest"
          DL_URL="$(curl -fsSL "$API_URL" \
            | jq -r '.assets[]
                     | select(.name | test("linux.*(amd64|x86_64)"; "i"))
                     | .browser_download_url' \
            | head -n1)"

          if [[ -z "${DL_URL:-}" ]]; then
            echo "❌ Konnte keine passende linux-amd64 Binary finden!"
            echo "👉 Prüfe https://github.com/cncf/landscape2/releases manuell."
            exit 1
          fi

          echo "⬇️  Downloading: $DL_URL"
          curl -fsSL "$DL_URL" -o "$HOME/bin/landscape2"
          chmod +x "$HOME/bin/landscape2"
          echo "$HOME/bin" >> "$GITHUB_PATH"

          echo "✅ Installation abgeschlossen:"
          which landscape2
          landscape2 --version || true

      # 3️⃣ Deine Landscape-Seite bauen
      - name: Build site
        shell: bash
        run: |
          landscape2 build \
            --data-file data.yml \
            --settings-file settings.yml \
            --guide-file guide.yml \
            --logos-path my-landscape \
            --output-dir site

      # 4️⃣ Output für GitHub Pages hochladen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  # 5️⃣ Deployment auf GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
