name: Build & Deploy Landscape

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install landscape2
        shell: bash
        run: |
          set -Eeuo pipefail
          VERSION="v0.12.0"
          curl -fsSL "https://github.com/cncf/landscape2/releases/download/${VERSION}/landscape2-installer.sh" | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          which landscape2
          landscape2 --version || true

      # Build: logos are in hosted_logos/ at repo root
      - name: Build site
        shell: bash
        run: |
          set -euo pipefail
          landscape2 build --data-file data.yml --settings-file settings.yml --guide-file guide.yml --logos-path hosted_logos --output-dir site

      # (Safety) Prefix absolute / paths so they work under /my-landscape/
      - name: Prefix absolute paths for Project Pages
        env:
          BASE: "/my-landscape"
        run: |
          find site -name "*.html" -print0 | while IFS= read -r -d '' f; do
            sed -i -E "s#(src|href)=\"/+#\1=\"${BASE}/#g" "$f"
          done

      # Optional: quick debug if something breaks
      - name: Debug output
        run: |
          echo "Files in site/:"
          find site -maxdepth 2 -type f | sort

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
