name: Build & Deploy Landscape

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installiere landscape2 via offizielles Installer-Script (empfohlen)
      - name: Install landscape2
        shell: bash
        run: |
          set -Eeuo pipefail
          # Nimm eine veröffentlichte Version aus den Releases (z.B. v0.12.0)
          VERSION="v0.12.0"
          curl -fsSL "https://github.com/cncf/landscape2/releases/download/${VERSION}/landscape2-installer.sh" | sh
          # Der Installer legt die Binary typischerweise unter ~/.local/bin ab:
          export PATH="$HOME/.local/bin:$PATH"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          which landscape2
          landscape2 --version || true

      - name: Build site
        shell: bash
        run: |
          landscape2 build \
            --data-file data.yml \
            --settings-file settings.yml \
            --guide-file guide.yml \
            --logos-path my-landscape/ \
            --output-dir site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
