name: Build & Deploy Landscape

on:
  push:
    branches: [ main ]      # führt den Build bei jedem Commit auf main aus
  workflow_dispatch:         # erlaubt manuelles Starten

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Repository-Inhalt holen
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ landscape2 CLI installieren (stabiler Download)
      - name: Install landscape2
        shell: bash
        run: |
          set -Eeuo pipefail
          VERSION="v1.1.0"   # feste Version
          TARGET="$HOME/bin/landscape2"
          mkdir -p "$(dirname "$TARGET")"
          curl -fL "https://github.com/cncf/landscape2/releases/download/${VERSION}/landscape2-linux-amd64" -o "$TARGET"
          chmod +x "$TARGET"
          echo "$HOME/bin" >> "$GITHUB_PATH"
          ls -l "$TARGET"
          which landscape2
          landscape2 --version || true

      # 3️⃣ Landscape-Website bauen
      - name: Build site
        shell: bash
        run: |
          landscape2 build \
            --data-file data.yml \
            --settings-file settings.yml \
            --guide-file guide.yml \
            --logos-path my-landscape \
            --output-dir site

      # 4️⃣ Für GitHub Pages bereitstellen
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
