name: Build Landscape from LFX

on:
  workflow_dispatch:           # manuell starten
  schedule:
    - cron: "0 4 * * *"        # optional: täglich 04:00 UTC neu bauen

permissions:
  contents: write              # nötig, um in gh-pages zu pushen

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # (Optional) Damit im Log klar ist, was gebaut wird
      - name: Show repo head
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref:        ${{ github.ref }}"

      # LFX Landscape Tools ausführen – baut & pushed nach gh-pages
      - name: Build via LFX tools
        uses: jmertic/lfx-landscape-tools@20a188cdc3f2ee0318047b50de7e9b75b8f48268 # 20250528
        with:
          project_processing: skip          # übliche Default-Einstellung
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      # (Optional) Zeig letzten Commit auf gh-pages im Log
      - name: Print gh-pages head
        run: |
          git fetch origin gh-pages:gh-pages
          git log -1 --pretty=oneline gh-pages || true
